export const GET_QUESTION = "GET_QUESTION";
export const QUESTION_LOADING = "QUESTION_LOADING";
export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const ADD_QUESTION = "ADD_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const EDIT_QUESTION = "EDIT_QUESTION";
export const PICK_QUESTION = "PICK_QUESTION";
